/*
 * Data for the Sagrada Família "Our Father" door.
 *
 * boxes: [x, y, width, height] in PERCENT of door.jpg (0-100). A language can have several boxes
 *        (the door repeats some lines). Empty array = not located on the photo yet.
 * text:  full Our Father. Empty string = still to be filled in.
 * verify: true = text written from memory for a hard language; please check against a trusted source.
 * note:  shown under the language name (e.g. only the "Our Father" heading was readable on the door).
 *
 * Box positions were estimated by eye from the photos. Open index.html?edit to redraw any box.
 */
window.LANGS = [
  { id: "ca", name: "Catalan", native: "Català", boxes: [[21, 50.8, 61, 4.6], [1, 54.3, 97.5, 4.4]],
    note: "The big central lettering: the whole prayer is in Catalan.",
    text: "Pare nostre, que esteu en el cel, sigui santificat el vostre nom, vingui a nosaltres el vostre Regne, faci's la vostra voluntat així a la terra com es fa en el cel. El nostre pa de cada dia doneu-nos, Senyor, el dia d'avui, i perdoneu les nostres culpes així com nosaltres perdonem els nostres deutors, i no permeteu que caiguem en la temptació, ans deslliureu-nos de qualsevol mal. Amén." },
  { id: "sq", name: "Albanian", native: "Shqip", boxes: [[61, 5.2, 34, 1.5]],
    text: "Ati ynë që je në qiej, u shenjtëroftë emri yt, ardhtë mbretëria jote, u bëftë vullneti yt, siç në qiell edhe mbi tokë. Bukën tonë të përditshme jepna neve sot, dhe falna fajet tona, siç ua falim edhe ne fajtorëve tanë, dhe mos na shtjer në tundim, por na shpëto nga i ligu. Amen." },
  { id: "de", name: "German", native: "Deutsch", boxes: [[3, 27.6, 25, 1.8], [56, 6.9, 9, 1.4]],
    text: "Vater unser im Himmel, geheiligt werde dein Name. Dein Reich komme. Dein Wille geschehe, wie im Himmel so auf Erden. Unser tägliches Brot gib uns heute. Und vergib uns unsere Schuld, wie auch wir vergeben unsern Schuldigern. Und führe uns nicht in Versuchung, sondern erlöse uns von dem Bösen. Denn dein ist das Reich und die Kraft und die Herrlichkeit in Ewigkeit. Amen." },
  { id: "zgh", name: "Amazigh (Berber)", native: "ⵜⴰⵎⴰⵣⵉⵖⵜ", boxes: [[3, 14.2, 22, 2]], note: "Written in Tifinagh script.",
    text: "" },
  { id: "vi", name: "Vietnamese", native: "Tiếng Việt", boxes: [[3, 40.6, 25, 1.6], [64, 91.7, 36, 1.4], [50, 24.4, 15, 1.3]],
    text: "Lạy Cha chúng con ở trên trời, chúng con nguyện danh Cha cả sáng, nước Cha trị đến, ý Cha thể hiện dưới đất cũng như trên trời. Xin Cha cho chúng con hôm nay lương thực hằng ngày, và tha nợ chúng con, như chúng con cũng tha kẻ có nợ chúng con. Xin chớ để chúng con sa chước cám dỗ, nhưng cứu chúng con cho khỏi sự dữ. Amen." },
  { id: "ar", name: "Arabic", native: "العربية", dir: "rtl", boxes: [[78, 33.8, 18, 1.4], [55, 8.3, 14, 1.5], [8, 24.6, 14, 1.8]],
    text: "أبانا الذي في السماوات، ليتقدس اسمك، ليأت ملكوتك، لتكن مشيئتك كما في السماء كذلك على الأرض. خبزنا كفافنا أعطنا اليوم، واغفر لنا ذنوبنا كما نغفر نحن أيضاً للمذنبين إلينا، ولا تدخلنا في تجربة، لكن نجنا من الشرير. آمين." },
  { id: "arc", name: "Aramaic", native: "ܐܪܡܝܐ", dir: "rtl", boxes: [[2, 37.4, 29, 3], [75, 11.3, 20, 1.7]], verify: true,
    note: "The door writes Aramaic in Hebrew letters; this text is the Syriac (Peshitta) form.",
    text: "ܐܒܘܢ ܕܒܫܡܝܐ ܢܬܩܕܫ ܫܡܟ ܬܐܬܐ ܡܠܟܘܬܟ ܢܗܘܐ ܨܒܝܢܟ ܐܝܟܢܐ ܕܒܫܡܝܐ ܐܦ ܒܐܪܥܐ ܗܒ ܠܢ ܠܚܡܐ ܕܣܘܢܩܢܢ ܝܘܡܢܐ ܘܫܒܘܩ ܠܢ ܚܘܒܝܢ ܐܝܟܢܐ ܕܐܦ ܚܢܢ ܫܒܩܢ ܠܚܝܒܝܢ ܘܠܐ ܬܥܠܢ ܠܢܣܝܘܢܐ ܐܠܐ ܦܨܢ ܡܢ ܒܝܫܐ ܐܡܝܢ" },
  { id: "an", name: "Aranese (Occitan)", native: "Aranés", boxes: [[66, 38.5, 30, 1.4], [3, 59, 23, 1.8]],
    text: "Pairenòstre, qu'ès enes cèls, que siá santificat eth tòn nòm, que vengue eth tòn règne, que sigue hèta era tua votentat, atau coma ena tèrra, enes cèls. Dà-mos auè eth pan nòste de cada dia, e perdona-mos es nòsti offenses, atau coma nosati perdonam as qu'ac an offenut, e non mos hages cadir en era temptacion, mès deliura-mos deth mau. Amen." },
  { id: "bg", name: "Bulgarian", native: "Български", boxes: [[70, 32, 26, 1.3], [4, 23.8, 19, 1.8], [52, 86, 25, 1.2]],
    text: "Отче наш, Който си на небесата, да се свети Твоето име, да дойде Твоето царство, да бъде Твоята воля, както на небето, така и на земята. Хляба ни насъщния дай ни днес, и прости нам дълговете ни, както и ние прощаваме на нашите длъжници, и не ни въвеждай в изкушение, но ни избави от лукавия. Амин." },
  { id: "es", name: "Spanish", native: "Español", boxes: [[66, 6.9, 29, 1.6], [56, 66.4, 40, 2]],
    text: "Padre nuestro, que estás en el cielo, santificado sea tu Nombre; venga a nosotros tu reino; hágase tu voluntad en la tierra como en el cielo. Danos hoy nuestro pan de cada día; perdona nuestras ofensas, como también nosotros perdonamos a los que nos ofenden; no nos dejes caer en la tentación, y líbranos del mal. Amén." },
  { id: "cs", name: "Czech", native: "Čeština", boxes: [[67, 42.8, 23, 1.3], [77, 86, 23, 1.3]],
    text: "Otče náš, jenž jsi na nebesích, posvěť se jméno Tvé, přijď království Tvé, buď vůle Tvá jako v nebi, tak i na zemi. Chléb náš vezdejší dej nám dnes, a odpusť nám naše viny, jako i my odpouštíme našim viníkům, a neuveď nás v pokušení, ale zbav nás od zlého. Amen." },
  { id: "zh", name: "Chinese", native: "中文", boxes: [[4, 30.4, 27, 1.8], [58, 16, 19, 1.6], [55, 33.2, 22, 1.6]],
    text: "我們在天上的父,願你的名被尊為聖。願你的國來臨。願你的旨意奉行在地上,如同在天上。求你今天賜給我們日用的食糧。求你寬恕我們的罪過,如同我們寬恕別人一樣。不要讓我們陷於誘惑,但救我們脫離凶惡。阿們。" },
  { id: "cop", name: "Coptic", native: "Ⲙⲉⲧⲣⲉⲙ̀ⲛⲭⲏⲙⲓ", boxes: [[3, 35.6, 19, 1.6]], verify: true,
    text: "Ⲡⲉⲛⲓⲱⲧ ⲉⲧϧⲉⲛ ⲛⲓⲫⲏⲟⲩⲓ ⲙⲁⲣⲉϥⲧⲟⲩⲃⲟ ⲛϫⲉ ⲡⲉⲕⲣⲁⲛ ⲙⲁⲣⲉⲥⲓ ⲛϫⲉ ⲧⲉⲕⲙⲉⲧⲟⲩⲣⲟ ⲫⲁⲓ ⲉⲧⲉⲣⲉⲧⲉⲕⲟⲩⲱϣ ⲛⲁϣⲱⲡⲓ ϧⲉⲛ ⲧⲫⲉ ⲙⲛ ϩⲓϫⲉⲛ ⲡⲕⲁϩⲓ ⲡⲉⲛⲱⲓⲕ ⲛⲧⲉ ⲣⲁⲥϯ ⲙⲏⲧⲁⲓ ⲛⲁⲛ ⲙ̀ⲫⲟⲟⲩ ⲁⲩⲱ ⲭⲁ ⲛⲉⲛⲟⲃⲓ ⲛⲁⲛ ⲉⲃⲟⲗ ⲕⲁⲧⲁ ϩⲱⲥ ⲁⲛⲟⲛ ϩⲱⲛ ⲉⲛⲭⲱ ⲉⲃⲟⲗ ⲛⲛⲉⲛⲉⲧⲁϩⲟⲃⲓ ⲛⲁⲛ ⲁⲩⲱ ⲙ̀ⲡⲉⲣⲉⲛⲧⲉⲛ ⲉϧⲟⲩⲛ ⲉⲡⲓⲣⲁⲥⲙⲟⲥ ⲁⲗⲗⲁ ⲛⲁϩⲙⲉⲛ ⲉⲃⲟⲗϩⲁ ⲡⲓⲡⲉⲧϩⲱⲟⲩ" },
  { id: "ko", name: "Korean", native: "한국어", boxes: [[76, 58.3, 20, 1.5], [2, 74.2, 20, 1.4]],
    text: "하늘에 계신 우리 아버지, 아버지의 이름이 거룩히 빛나시며, 나라가 임하시며, 뜻이 하늘에서와 같이 땅에서도 이루어지소서. 오늘 저희에게 일용할 양식을 주시고, 저희에게 잘못한 이를 저희가 용서하오니 저희 죄를 용서하시고, 저희를 유혹에 빠지지 말게 하시고 악에서 구하소서. 아멘." },
  { id: "hr", name: "Croatian", native: "Hrvatski", boxes: [[2, 88.5, 31, 1.6]],
    text: "Oče naš, koji jesi na nebesima, sveti se ime tvoje, dođi kraljevstvo tvoje, budi volja tvoja, kako na nebu tako i na zemlji. Kruh naš svagdanji daj nam danas, i otpusti nam duge naše, kao što i mi otpuštamo dužnicima našim, i ne uvedi nas u napast, nego izbavi nas od zla. Amen." },
  { id: "da", name: "Danish", native: "Dansk", boxes: [[57, 83, 22, 1.4]],
    text: "Fader vor, du som er i himlene! Helliget vorde dit navn; komme dit rige; ske din vilje som i himlen, således også på jorden. Giv os i dag vort daglige brød; og forlad os vor skyld, som også vi forlader vore skyldnere; og led os ikke ind i fristelse, men fri os fra det onde. Amen." },
  { id: "sl", name: "Slovenian", native: "Slovenščina", boxes: [[79, 83, 21, 1.4]],
    text: "Oče naš, ki si v nebesih, posvečeno bodi tvoje ime, pridi k nam tvoje kraljestvo, zgodi se tvoja volja kakor v nebesih tako na zemlji. Daj nam danes naš vsakdanji kruh in odpusti nam naše dolge, kakor tudi mi odpuščamo svojim dolžnikom, in ne vpelji nas v skušnjavo, temveč reši nas hudega. Amen." },
  { id: "eo", name: "Esperanto", native: "Esperanto", boxes: [[70, 94.4, 28, 1.4], [76, 64.4, 20, 1.4], [2, 77, 25, 1.3]],
    text: "Patro nia, kiu estas en la ĉielo, via nomo estu sanktigata. Venu via regno, plenumiĝu via volo, kiel en la ĉielo, tiel ankaŭ sur la tero. Nian panon ĉiutagan donu al ni hodiaŭ. Kaj pardonu al ni niajn ŝuldojn, kiel ankaŭ ni pardonas al niaj ŝuldantoj. Kaj ne konduku nin en tentadon, sed liberigu nin de la malbono. Amen." },
  { id: "et", name: "Estonian", native: "Eesti", boxes: [[4, 18, 16, 1.7]], note: "Only the \"Meie isa\" heading was readable on the photo.",
    text: "Meie Isa, kes sa oled taevas, pühitsetud olgu sinu nimi, sinu riik tulgu, sinu tahtmine sündigu nagu taevas, nõnda ka maa peal. Meie igapäevast leiba anna meile tänapäev ja anna meile andeks meie võlad, nagu meie andeks anname oma võlglastele, ja ära saada meid kiusatusse, vaid päästa meid ära kurjast. Sest sinu päralt on riik ja vägi ja au igavesti. Aamen." },
  { id: "fi", name: "Finnish", native: "Suomi", boxes: [[57, 21.7, 39, 1.6], [56, 76, 40, 1.5]],
    text: "Isä meidän, joka olet taivaissa. Pyhitetty olkoon sinun nimesi. Tulkoon sinun valtakuntasi. Tapahtukoon sinun tahtosi myös maan päällä niin kuin taivaassa. Anna meille tänäänkin meidän jokapäiväinen leipämme. Ja anna meille meidän syntimme anteeksi, niin kuin mekin anteeksi annamme niille, jotka ovat meitä vastaan syyllistyneet. Äläkä saata meitä kiusaukseen, vaan päästä meidät pahasta. Sillä sinun on valtakunta ja voima ja kunnia iankaikkisesti. Aamen." },
  { id: "fr", name: "French", native: "Français", boxes: [[4, 15.6, 29, 1.7], [51, 40, 15, 1.1]],
    text: "Notre Père, qui es aux cieux, que ton nom soit sanctifié, que ton règne vienne, que ta volonté soit faite sur la terre comme au ciel. Donne-nous aujourd'hui notre pain de ce jour. Pardonne-nous nos offenses, comme nous pardonnons aussi à ceux qui nous ont offensés. Et ne nous soumets pas à la tentation, mais délivre-nous du Mal. Amen." },
  { id: "ga", name: "Irish Gaelic", native: "Gaeilge", boxes: [[68, 81.3, 32, 1.6]],
    text: "Ár nAthair atá ar neamh, go naofar d'ainm, go dtaga do ríocht, go ndéantar do thoil ar an talamh mar a dhéantar ar neamh. Ár n-arán laethúil tabhair dúinn inniu, agus maith dúinn ár bhfiacha mar a mhaithimid dár bhféichiúna féin, agus ná lig sinn i gcathú, ach saor sinn ó olc. Amen." },
  { id: "gl", name: "Galician", native: "Galego", boxes: [[68, 40, 28, 1.4], [56, 11.5, 19, 1.3], [5, 11.8, 22, 1.8]],
    text: "Pai noso que estás no ceo, santificado sexa o teu nome, veña a nós o teu reino, fágase a túa vontade na terra coma no ceo. O noso pan de cada día dánosllo hoxe; e perdóanos as nosas ofensas, coma nós perdoamos a quen nos ten ofendido; e non nos deixes caer na tentación, mais líbranos do mal. Amén." },
  { id: "el", name: "Greek", native: "Ελληνικά", boxes: [[64, 24.4, 32, 1.3], [55, 37, 41, 1.5], [5, 17, 29, 1.5]],
    text: "Πάτερ ἡμῶν ὁ ἐν τοῖς οὐρανοῖς, ἁγιασθήτω τὸ ὄνομά σου, ἐλθέτω ἡ βασιλεία σου, γενηθήτω τὸ θέλημά σου, ὡς ἐν οὐρανῷ καὶ ἐπὶ τῆς γῆς. Τὸν ἄρτον ἡμῶν τὸν ἐπιούσιον δὸς ἡμῖν σήμερον, καὶ ἄφες ἡμῖν τὰ ὀφειλήματα ἡμῶν, ὡς καὶ ἡμεῖς ἀφίεμεν τοῖς ὀφειλέταις ἡμῶν, καὶ μὴ εἰσενέγκῃς ἡμᾶς εἰς πειρασμόν, ἀλλὰ ῥῦσαι ἡμᾶς ἀπὸ τοῦ πονηροῦ. Ἀμήν." },
  { id: "gn", name: "Guaraní", native: "Avañe'ẽ", boxes: [[65, 18, 14, 1.3]], note: "Position is a best guess (\"…eme'ẽ … ko árape\").",
    text: "" },
  { id: "he", name: "Hebrew", native: "עברית", dir: "rtl", boxes: [[77, 16, 19, 1.5], [29, 29.2, 10, 1.6]], verify: true,
    text: "אבינו שבשמים, יתקדש שמך, תבוא מלכותך, יעשה רצונך כאשר בשמים כן בארץ. את לחם חוקנו תן לנו היום, וסלח לנו על חטאינו, כשם שסולחים אנחנו לחוטאים לנו, ואל תביאנו לידי נסיון, כי אם הצילנו מן הרע. אמן." },
  { id: "hu", name: "Hungarian", native: "Magyar", boxes: [[62, 25.6, 34, 1.4]],
    text: "Mi Atyánk, aki a mennyekben vagy, szenteltessék meg a te neved. Jöjjön el a te országod. Legyen meg a te akaratod, amint a mennyben, úgy a földön is. Mindennapi kenyerünket add meg nekünk ma, és bocsásd meg vétkeinket, miképpen mi is megbocsátunk az ellenünk vétkezőknek. És ne vígy minket kísértésbe, de szabadíts meg a gonosztól. Mert tiéd az ország, a hatalom és a dicsőség mindörökké. Ámen." },
  { id: "id", name: "Indonesian", native: "Bahasa Indonesia", boxes: [[4, 8.3, 10, 1.5]], note: "Only the \"Bapa kami\" heading was readable on the photo.",
    text: "Bapa kami yang di surga, dikuduskanlah nama-Mu, datanglah Kerajaan-Mu, jadilah kehendak-Mu di bumi seperti di surga. Berilah kami pada hari ini makanan kami yang secukupnya, dan ampunilah kami akan kesalahan kami, seperti kami juga mengampuni orang yang bersalah kepada kami, dan janganlah membawa kami ke dalam pencobaan, tetapi lepaskanlah kami daripada yang jahat. Amin." },
  { id: "en", name: "English", native: "English", boxes: [[70, 14.5, 26, 1.5], [72, 44.2, 24, 1.3], [76, 29.8, 20, 1.3]],
    text: "Our Father, who art in heaven, hallowed be thy name; thy kingdom come; thy will be done, on earth as it is in heaven. Give us this day our daily bread; and forgive us our trespasses, as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil. Amen." },
  { id: "is", name: "Icelandic", native: "Íslenska", boxes: [[31, 18.2, 7, 1.6]], note: "Only the \"Faðir vor\" heading was readable on the photo.",
    text: "Faðir vor, þú sem ert á himnum, helgist þitt nafn, til komi þitt ríki, verði þinn vilji, svo á jörðu sem á himni. Gef oss í dag vort daglegt brauð, og fyrirgef oss vorar skuldir, svo sem vér og fyrirgefum vorum skuldunautum, og eigi leið þú oss í freistni, heldur frelsa oss frá illu. Því að þitt er ríkið, mátturinn og dýrðin að eilífu. Amen." },
  { id: "it", name: "Italian", native: "Italiano", boxes: [[67, 41.4, 29, 1.4], [14, 21.4, 25, 1.7]],
    text: "Padre nostro, che sei nei cieli, sia santificato il tuo nome, venga il tuo regno, sia fatta la tua volontà come in cielo così in terra. Dacci oggi il nostro pane quotidiano, e rimetti a noi i nostri debiti come noi li rimettiamo ai nostri debitori, e non abbandonarci alla tentazione, ma liberaci dal male. Amen." },
  { id: "ja", name: "Japanese", native: "日本語", boxes: [[72, 13.1, 24, 1.3]],
    text: "天におられるわたしたちの父よ、み名が聖とされますように。み国が来ますように。みこころが天に行われるとおり地にも行われますように。わたしたちの日ごとの糧を今日もお与えください。わたしたちの罪をおゆるしください。わたしたちも人をゆるします。わたしたちを誘惑におちいらせず、悪からお救いください。アーメン。" },
  { id: "la", name: "Latin", native: "Latina", boxes: [[69, 8.4, 26, 1.5], [5, 13, 26, 1.5]],
    text: "Pater noster, qui es in caelis, sanctificetur nomen tuum; adveniat regnum tuum; fiat voluntas tua, sicut in caelo et in terra. Panem nostrum quotidianum da nobis hodie; et dimitte nobis debita nostra, sicut et nos dimittimus debitoribus nostris; et ne nos inducas in tentationem; sed libera nos a malo. Amen." },
  { id: "nl", name: "Dutch", native: "Nederlands", boxes: [[68, 45.3, 28, 1.3], [3, 26.5, 24, 1.5]],
    text: "Onze Vader, die in de hemelen zijt, uw naam worde geheiligd; uw rijk kome; uw wil geschiede op aarde zoals in de hemel. Geef ons heden ons dagelijks brood; en vergeef ons onze schulden, zoals ook wij aan anderen hun schulden vergeven; en leid ons niet in bekoring, maar verlos ons van het kwade. Amen." },
  { id: "no", name: "Norwegian", native: "Norsk", boxes: [[63, 26.8, 21, 1.3]],
    text: "Fader vår, du som er i himmelen! La ditt navn holdes hellig. La ditt rike komme. La din vilje skje på jorden som i himmelen. Gi oss i dag vårt daglige brød. Og forlat oss vår skyld, som vi òg forlater våre skyldnere. Og led oss ikke inn i fristelse, men frels oss fra det onde. For riket er ditt og makten og æren i evighet. Amen." },
  { id: "pl", name: "Polish", native: "Polski", boxes: [[62, 23.2, 34, 1.3], [4, 19.2, 33, 2]],
    text: "Ojcze nasz, któryś jest w niebie, święć się imię Twoje, przyjdź królestwo Twoje, bądź wola Twoja jako w niebie tak i na ziemi. Chleba naszego powszedniego daj nam dzisiaj, i odpuść nam nasze winy, jako i my odpuszczamy naszym winowajcom, i nie wódź nas na pokuszenie, ale nas zbaw ode złego. Amen." },
  { id: "pt", name: "Portuguese", native: "Português", boxes: [[67, 90, 33, 1.4], [67, 47.8, 29, 1.2], [4, 33, 24, 1.5]],
    text: "Pai nosso, que estais nos céus, santificado seja o vosso nome, venha a nós o vosso reino, seja feita a vossa vontade assim na terra como no céu. O pão nosso de cada dia nos dai hoje, perdoai-nos as nossas ofensas assim como nós perdoamos a quem nos tem ofendido, e não nos deixeis cair em tentação, mas livrai-nos do mal. Ámen." },
  { id: "qu", name: "Quechua", native: "Runasimi", boxes: [[57, 18, 8, 1.3]], note: "Position is a best guess (the \"Kanaqninchis…\" line).",
    text: "" },
  { id: "ro", name: "Romanian", native: "Română", boxes: [[4, 20.8, 34, 1.6]],
    text: "Tatăl nostru, Care eşti în ceruri, sfinţească-Se numele Tău, vie împărăţia Ta, fie voia Ta, precum în cer aşa şi pe pământ. Pâinea noastră cea de toate zilele dă-ne-o nouă astăzi, şi ne iartă nouă greşealele noastre, precum şi noi iertăm greşiţilor noştri, şi nu ne duce pe noi în ispită, ci ne izbăveşte de cel rău. Amin." },
  { id: "ru", name: "Russian", native: "Русский", boxes: [[72, 69.8, 24, 1.4], [3, 33.1, 24, 1.5]],
    text: "Отче наш, сущий на небесах! Да святится имя Твоё, да приидет Царствие Твоё, да будет воля Твоя и на земле, как на небе. Хлеб наш насущный дай нам на сей день; и прости нам долги наши, как и мы прощаем должникам нашим; и не введи нас в искушение, но избави нас от лукавого. Аминь." },
  { id: "sa", name: "Sanskrit", native: "संस्कृतम्", boxes: [[73, 62, 23, 1.4], [78, 89, 22, 1.4]], verify: true,
    text: "अस्माकं पिता, यः स्वर्गे वससि, तव नाम पवित्रं भवतु; तव राज्यम् आगच्छतु; तव इच्छा स्वर्गे इव पृथिव्यामपि पूर्यताम्। अस्माकं प्रयोजनीयम् आहारम् अद्य अस्मभ्यं देहि; अस्माकम् अपराधान् क्षमस्व, यथा वयम् अपराधिनां क्षमामहे; अस्मान् परीक्षायां मा नय, किन्तु दुष्टात् अस्मान् रक्ष। आमेन्।" },
  { id: "sc", name: "Sardinian", native: "Sardu", boxes: [[70, 20.7, 26, 1.5]], verify: true,
    text: "Babbu nostru, chi ses in sos chelos, santificadu siat su nomen tuo, benzat su rennu tuo, fatta siat sa voluntade tua, comente in su chelu gasi in terra. Dona-nos oe su pane nostru de cada die, e perdona-nos sos peccados nostros, comente nois perdonamus a sos depidores nostros, e non nos lasses ruer in tentassione, ma lìberanos dae su male. Amen." },
  { id: "sr", name: "Serbian", native: "Српски", boxes: [], note: "Not located on the photo yet (Cyrillic, very similar to the Russian, Bulgarian and Ukrainian lines).",
    text: "Оче наш, који си на небесима, да се свети име Твоје, да дође царство Твоје, да буде воља Твоја, како на небу тако и на земљи. Хлеб наш насушни дај нам данас, и опрости нам дугове наше, као што и ми остављамо дужницима својим, и не уведи нас у искушење, но избави нас од злога. Амин." },
  { id: "sw", name: "Swahili", native: "Kiswahili", boxes: [[2, 36, 25, 1.4], [28, 34.8, 7, 1.5]],
    text: "Baba yetu uliye mbinguni, jina lako litukuzwe. Ufalme wako uje. Mapenzi yako yatimizwe duniani kama mbinguni. Utupe leo mkate wetu wa kila siku. Utusamehe makosa yetu, kama nasi tunavyowasamehe waliotukosea. Usitutie katika kishawishi, lakini utuokoe na yule mwovu. Amina." },
  { id: "sv", name: "Swedish", native: "Svenska", boxes: [[78, 28.7, 18, 1.3]],
    text: "Fader vår, som är i himmelen! Helgat varde ditt namn; tillkomme ditt rike; ske din vilja, såsom i himmelen, så ock på jorden. Vårt dagliga bröd giv oss i dag; och förlåt oss våra skulder, såsom ock vi förlåta dem oss skyldiga äro; och inled oss icke i frestelse, utan fräls oss ifrån ondo. Ty riket är ditt, och makten och härligheten, i evighet. Amen." },
  { id: "tl", name: "Tagalog", native: "Tagalog", boxes: [[52, 35.3, 44, 1.4], [3, 63.8, 17, 1.3]],
    text: "Ama namin, sumasalangit Ka, sambahin ang pangalan Mo. Mapasaamin ang kaharian Mo. Sundin ang loob Mo, dito sa lupa, gaya nang sa langit. Bigyan Mo po kami ngayon ng aming kakanin sa araw-araw, at patawarin Mo po kami sa aming mga sala, para nang pagpapatawad namin sa nagkakasala sa amin; at huwag Mo po kaming ipahintulot sa tukso, at iadya Mo kami sa lahat ng masama. Amen." },
  { id: "bo", name: "Tibetan", native: "བོད་སྐད་", boxes: [[65, 18.9, 31, 1.5]],
    text: "" },
  { id: "uk", name: "Ukrainian", native: "Українська", boxes: [[66, 30.5, 30, 1.4], [2, 72.5, 20, 1.5]],
    text: "Отче наш, що єси на небесах, да святиться ім'я Твоє, да прийде Царство Твоє, да буде воля Твоя, як на небі, так і на землі. Хліб наш насущний дай нам сьогодні, і прости нам провини наші, як і ми прощаємо винуватцям нашим, і не введи нас у спокусу, але визволи нас від лукавого. Амінь." },
  { id: "eu", name: "Basque", native: "Euskara", boxes: [[5, 9, 22, 1.9], [2, 79.2, 28, 1.6]],
    text: "Gure Aita, zeruetan zaudena, santu izan bedi zure izena, etor bedi zure erreinua, egin bedi zure nahia, zeruan bezala lurrean ere. Emaiguzu gaur egun honetako ogia, eta barkatu gure zorrak, geuk ere gure zordunei barkatzen diegun bezala, eta ez gu tentaldian sartu, baina atera gaitzazu gaitzetik. Amen." },
  { id: "wo", name: "Wolof", native: "Wolof", boxes: [[27, 10.7, 11, 1.4], [2, 92.8, 25, 1.5], [68, 28.6, 10, 1.3]],
    text: "" }
];
